apiVersion: v1
kind: Service
metadata:
  name: k8s-web2-ap
spec:
  type: LoadBalancer
  selector:
    app: k8s-web2-ap
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web2-ap
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-web2-ap
  template:
    metadata:
      labels:
        app: k8s-web2-ap
    spec:
      containers:
      - image: lychee3/k8s-web2-ap:1.0
        name: k8s-web2-ap
        env:
        - name: DB_HOST
          value: k8s-web2-db
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: k8s-web2-secret
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: k8s-web2-secret
              key: password
        - name: DB_DATABASE
          value: mirumo-db
        ports:
        - containerPort: 3000
          name: k8s-web2-ap