apiVersion: v1
kind: Service
metadata:
  name: k8s-web2-db
spec:
  ports:
  - port: 3306
  selector:
    app: k8s-web2-db
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-web2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web2-db
spec:
  selector:
    matchLabels:
      app: k8s-web2-db
  template:
    metadata:
      labels:
        app: k8s-web2-db
    spec:
      containers:
      - image: lychee3/k8s-web2-db:1.0 
        name: k8s-web2-db
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: k8s-web2-secret
              key: root_password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: k8s-web2-secret
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: k8s-web2-secret
              key: password
        ports:
        - containerPort: 3306
          name: k8s-web2-db
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: k8s-web2-pvc