apiVersion: v1
kind: Service
metadata:
  name: node-sample-db
spec:
  ports:
  - port: 3306
  selector:
    app: node-sample-db
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-sample-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-sample-db
spec:
  selector:
    matchLabels:
      app: node-sample-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: node-sample-db
    spec:
      containers:
      - image: lychee3/node-sample-db:1.0 
        name: node-sample-db
        env:
        - name: MYSQL_ROOT_PASSWORD
          # value: mysql
          valueFrom:
            secretKeyRef:
              name: node-sample-secret
              key: root_password
        - name: MYSQL_USER
          # value: koa
          valueFrom:
            secretKeyRef:
              name: node-sample-secret
              key: user
        - name: MYSQL_PASSWORD
          # value: koa
          valueFrom:
            secretKeyRef:
              name: node-sample-secret
              key: password
        ports:
        - containerPort: 3306
          name: node-sample-db
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: node-sample-db-pvc